### ISSUE TITLE
no masking

### ISSUE THREAD

**Issue by helloword12345678** [InitialBug/FastBiDAF#1]
thanks for sharing!
i found this code not do masking after  padding?is this right

**Comment by InitialBug** [comment]
@helloword12345678 you are right, I only did this during evaluating process and ignore the padded words. I don't know whether the padded words would affect the performance during the training process or not. Anyway, I will add this to my code and test whether the preformance improves. Thank you so much!

**Comment by InitialBug** [comment]
@helloword12345678 I have already added the mask to my code and it got a little improvement.
